#!/bin/bash

DIR=$(pwd) 

case "$1" in
  start)
    echo "-end-" | nc localhost 12565 &> /dev/null
    cd /deme/wwwcgi
    java -jar cgi.jar &
    cd $DIR
    ;;
  stop)
    echo "-end-" | nc localhost 12565
    ;;
  restart|reload)
    echo "-end-" | nc localhost 12565
    cd /deme/wwwcgi
    java -jar cgi.jar &
    cd $DIR
    ;;
  *)
    echo "Usage: jdmcgi_server {start|stop|restart|reload}"
    ;;
esac

